#DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runmate?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

# JPA Configuration
  spring:
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate.ddl-auto: update
      hibernate.format_sql: true
      hibernate.show_sql: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

