#DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runmate?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

#spring:
#  datasource:
#    db1:
#      jdbc-url: jdbc:mysql://localhost:3306/runmate?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    db2:
#      jdbc-url: jdbc:postgresql://localhost:5432/runmate
#      driver-class-name: org.postgresql.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379


# JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

