spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10e205.p.ssafy.io:3306/runmate?useSSL=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
  data:
    redis:
      port: 6379
      host: k10e205.p.ssafy.io
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
