spring:
  datasource:
    username: runmate
    password: ssafy

oauth:
  kakao:
    client_id: 4629570ae90c2ce6b716b0e007118f1d
    redirect_uri: http://localhost:8000/auth/kakao/code


jwt:
  expiration_time: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa